name: Test
on:
  - push

jobs:
  
  # Type Checks
  type_check:
    runs-on: ubuntu-latest
    name: Type Check
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./frontend
      - name: Type Check
        run: npm run type-check
        working-directory: ./frontend
